### ISSUE TITLE
example story

### ISSUE THREAD

**Issue by alexclaes** [alexclaes/nf-setup-linting#2]
## Value Proposition

**As a** ...(user, Author, logged in User...)
**I need** ...(describe the goal)
**to be able to** ...(describe the reason)

## Description

Scribble / design or text

## Acceptance Criteria

- [x] describe every scenario in detail
- [ ] e.g. All Inputs are required, show warning if empty.
- [x] ...

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [x] e.g. Components, Storybook, testing
- [x] ...
