### ISSUE TITLE
Display important details of a single product

### ISSUE THREAD

**Issue by alexclaes** [alexclaes/nf-setup-linting#3]
## Value Proposition

**As a** shop administrator
**I need** to see the details of a single product 
**to be able to** check if the data is correct.

## Description
![user-story-1-description-image](https://user-images.githubusercontent.com/7231474/166647756-27fdc1b6-59dd-48c5-8cdd-fc07fe2cd9d5.png)

## Acceptance Criteria
- [x] The product's name is displayed
- [x] The product's description is displayed
- [x] The product's price is displayed with a currency sign

## Tasks
- [ ] Create the data structure to hold the product details
- [ ] Create a component that receives product details via props and renders it
- [ ] Apply basic styling to distinguish between headline and dynamic values
- [ ] Add to Storybook
- [ ] Write test to check if data is rendered
